version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: nemesh
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: deliveries
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@localhost.com"
      PGADMIN_DEFAULT_PASSWORD: "12345678"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  db_data:
  pgadmin_data: